replicaCount: 1

image:
  repository: soumyasekhardey/fastapi-helm
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
